### ISSUE TITLE
WPA Button

### ISSUE THREAD

**Issue by apographon** [nicokaiser/rpi-camera-import#3]
It should be easy to use one of the PIO to enable a button for WPS connection.
A WLAN connection could then be even more easy to setup

**Comment by nicokaiser** [comment]
That's a nice idea. This device was initially planned for usage on the road, where no Wifi is available (that's why it can open its own Wifi: you can connect to it from you phone and debug if things go wrong), so I did not implement anything between "fixed Wifi configuration" and "provides access point".

Can you open a PR for this?
